const RAW = [
  ['GH', '233', 'Ghana'],
  ['US', '1', 'United States'],
  ['CA', '1', 'Canada'],
  ['GB', '44', 'United Kingdom'],
  ['AU', '61', 'Australia'],
  ['NZ', '64', 'New Zealand'],
  ['IE', '353', 'Ireland'],
  ['ZA', '27', 'South Africa'],
  ['NG', '234', 'Nigeria'],
  ['KE', '254', 'Kenya'],
  ['EG', '20', 'Egypt'],
  ['MA', '212', 'Morocco'],
  ['TN', '216', 'Tunisia'],
  ['DZ', '213', 'Algeria'],
  ['SN', '221', 'Senegal'],
  ['CI', '225', "Côte d'Ivoire"],
  ['CM', '237', 'Cameroon'],
  ['ET', '251', 'Ethiopia'],
  ['TZ', '255', 'Tanzania'],
  ['UG', '256', 'Uganda'],
  ['RW', '250', 'Rwanda'],
  ['MU', '230', 'Mauritius'],
  ['ZM', '260', 'Zambia'],
  ['ZW', '263', 'Zimbabwe'],
  ['MW', '265', 'Malawi'],
  ['BW', '267', 'Botswana'],
  ['NA', '264', 'Namibia'],
  ['MZ', '258', 'Mozambique'],
  ['AO', '244', 'Angola'],
  ['ML', '223', 'Mali'],
  ['BF', '226', 'Burkina Faso'],
  ['BJ', '229', 'Benin'],
  ['TG', '228', 'Togo'],
  ['NE', '227', 'Niger'],
  ['TD', '235', 'Chad'],
  ['CF', '236', 'Central African Republic'],
  ['CG', '242', 'Congo'],
  ['CD', '243', 'Democratic Republic of the Congo'],
  ['GA', '241', 'Gabon'],
  ['GQ', '240', 'Equatorial Guinea'],
  ['SL', '232', 'Sierra Leone'],
  ['LR', '231', 'Liberia'],
  ['GM', '220', 'Gambia'],
  ['GN', '224', 'Guinea'],
  ['GW', '245', 'Guinea-Bissau'],
  ['MR', '222', 'Mauritania'],
  ['SO', '252', 'Somalia'],
  ['DJ', '253', 'Djibouti'],
  ['ER', '291', 'Eritrea'],
  ['SS', '211', 'South Sudan'],
  ['MG', '261', 'Madagascar'],
  ['SC', '248', 'Seychelles'],
  ['KM', '269', 'Comoros'],
  ['CV', '238', 'Cape Verde'],
  ['ST', '239', 'São Tomé and Príncipe'],
  ['LS', '266', 'Lesotho'],
  ['SZ', '268', 'Eswatini'],
  ['DE', '49', 'Germany'],
  ['FR', '33', 'France'],
  ['IT', '39', 'Italy'],
  ['ES', '34', 'Spain'],
  ['PT', '351', 'Portugal'],
  ['NL', '31', 'Netherlands'],
  ['BE', '32', 'Belgium'],
  ['CH', '41', 'Switzerland'],
  ['AT', '43', 'Austria'],
  ['SE', '46', 'Sweden'],
  ['NO', '47', 'Norway'],
  ['DK', '45', 'Denmark'],
  ['FI', '358', 'Finland'],
  ['IS', '354', 'Iceland'],
  ['GR', '30', 'Greece'],
  ['PL', '48', 'Poland'],
  ['CZ', '420', 'Czech Republic'],
  ['SK', '421', 'Slovakia'],
  ['HU', '36', 'Hungary'],
  ['RO', '40', 'Romania'],
  ['BG', '359', 'Bulgaria'],
  ['RS', '381', 'Serbia'],
  ['HR', '385', 'Croatia'],
  ['SI', '386', 'Slovenia'],
  ['BA', '387', 'Bosnia and Herzegovina'],
  ['MK', '389', 'North Macedonia'],
  ['AL', '355', 'Albania'],
  ['ME', '382', 'Montenegro'],
  ['XK', '383', 'Kosovo'],
  ['LT', '370', 'Lithuania'],
  ['LV', '371', 'Latvia'],
  ['EE', '372', 'Estonia'],
  ['UA', '380', 'Ukraine'],
  ['MD', '373', 'Moldova'],
  ['BY', '375', 'Belarus'],
  ['LU', '352', 'Luxembourg'],
  ['MT', '356', 'Malta'],
  ['CY', '357', 'Cyprus'],
  ['MC', '377', 'Monaco'],
  ['LI', '423', 'Liechtenstein'],
  ['AD', '376', 'Andorra'],
  ['SM', '378', 'San Marino'],
  ['VA', '379', 'Vatican City'],
  ['RU', '7', 'Russia'],
  ['JP', '81', 'Japan'],
  ['CN', '86', 'China'],
  ['IN', '91', 'India'],
  ['KR', '82', 'South Korea'],
  ['KP', '850', 'North Korea'],
  ['SG', '65', 'Singapore'],
  ['MY', '60', 'Malaysia'],
  ['ID', '62', 'Indonesia'],
  ['PH', '63', 'Philippines'],
  ['TH', '66', 'Thailand'],
  ['VN', '84', 'Vietnam'],
  ['MM', '95', 'Myanmar'],
  ['KH', '855', 'Cambodia'],
  ['LA', '856', 'Laos'],
  ['BN', '673', 'Brunei'],
  ['TL', '670', 'Timor-Leste'],
  ['NP', '977', 'Nepal'],
  ['BD', '880', 'Bangladesh'],
  ['LK', '94', 'Sri Lanka'],
  ['PK', '92', 'Pakistan'],
  ['AF', '93', 'Afghanistan'],
  ['IR', '98', 'Iran'],
  ['IQ', '964', 'Iraq'],
  ['JO', '962', 'Jordan'],
  ['LB', '961', 'Lebanon'],
  ['IL', '972', 'Israel'],
  ['PS', '970', 'Palestine'],
  ['SA', '966', 'Saudi Arabia'],
  ['YE', '967', 'Yemen'],
  ['OM', '968', 'Oman'],
  ['AE', '971', 'United Arab Emirates'],
  ['QA', '974', 'Qatar'],
  ['BH', '973', 'Bahrain'],
  ['KW', '965', 'Kuwait'],
  ['TR', '90', 'Turkey'],
  ['AZ', '994', 'Azerbaijan'],
  ['GE', '995', 'Georgia'],
  ['AM', '374', 'Armenia'],
  ['SY', '963', 'Syria'],
  ['MN', '976', 'Mongolia'],
  ['KZ', '7', 'Kazakhstan'],
  ['UZ', '998', 'Uzbekistan'],
  ['TM', '993', 'Turkmenistan'],
  ['KG', '996', 'Kyrgyzstan'],
  ['TJ', '992', 'Tajikistan'],
  ['MX', '52', 'Mexico'],
  ['BR', '55', 'Brazil'],
  ['AR', '54', 'Argentina'],
  ['CO', '57', 'Colombia'],
  ['CL', '57', 'Chile'],
  ['PE', '51', 'Peru'],
  ['EC', '593', 'Ecuador'],
  ['VE', '58', 'Venezuela'],
  ['BO', '591', 'Bolivia'],
  ['PY', '595', 'Paraguay'],
  ['UY', '598', 'Uruguay'],
  ['GY', '592', 'Guyana'],
  ['SR', '597', 'Suriname'],
  ['GF', '594', 'French Guiana'],
  ['CR', '506', 'Costa Rica'],
  ['PA', '507', 'Panama'],
  ['GT', '502', 'Guatemala'],
  ['SV', '503', 'El Salvador'],
  ['HN', '504', 'Honduras'],
  ['NI', '505', 'Nicaragua'],
  ['BZ', '501', 'Belize'],
  ['CU', '53', 'Cuba'],
  ['DO', '1809', 'Dominican Republic'],
  ['HT', '509', 'Haiti'],
  ['JM', '1876', 'Jamaica'],
  ['TT', '1868', 'Trinidad and Tobago'],
  ['BS', '1242', 'Bahamas'],
  ['BB', '1246', 'Barbados'],
  ['DM', '1767', 'Dominica'],
  ['GD', '1473', 'Grenada'],
  ['KN', '1869', 'Saint Kitts and Nevis'],
  ['LC', '1758', 'Saint Lucia'],
  ['VC', '1784', 'Saint Vincent and the Grenadines'],
  ['AG', '1268', 'Antigua and Barbuda'],
  ['AW', '297', 'Aruba'],
  ['CW', '599', 'Curaçao'],
  ['BQ', '599', 'Bonaire'],
  ['SX', '1721', 'Sint Maarten'],
  ['MF', '590', 'Saint Martin'],
  ['GP', '590', 'Guadeloupe'],
  ['MQ', '596', 'Martinique'],
  ['RE', '262', 'Réunion'],
  ['YT', '262', 'Mayotte'],
  ['HK', '852', 'Hong Kong'],
  ['MO', '853', 'Macau'],
  ['TW', '886', 'Taiwan'],
  ['PR', '1787', 'Puerto Rico'],
  ['VI', '1340', 'U.S. Virgin Islands'],
  ['VG', '1284', 'British Virgin Islands'],
  ['KY', '1345', 'Cayman Islands'],
  ['BM', '1441', 'Bermuda'],
  ['GI', '350', 'Gibraltar'],
  ['FO', '298', 'Faroe Islands'],
  ['GL', '299', 'Greenland'],
  ['IM', '44', 'Isle of Man'],
  ['JE', '44', 'Jersey'],
  ['GG', '44', 'Guernsey'],
  ['FK', '500', 'Falkland Islands'],
  ['SJ', '4779', 'Svalbard'],
  ['AX', '358', 'Åland Islands'],
] as const;

export interface CountryEntry {
  code: string;
  dial: string;
  name: string;
}

export const ALL_COUNTRIES: CountryEntry[] = RAW
  .map(([code, dial, name]) => ({ code, dial, name }))
  .sort((a, b) => a.name.localeCompare(b.name));

export const COUNTRY_TO_DIAL: Record<string, string> = {};
export const CODE_TO_DIAL: Record<string, string> = {};
for (const c of ALL_COUNTRIES) {
  COUNTRY_TO_DIAL[c.name] = c.dial;
  CODE_TO_DIAL[c.code] = c.dial;
}

export function getFlagEmoji(code: string) {
  const c = code.toUpperCase().split('');
  if (c.length !== 2) return '';
  return String.fromCodePoint(0x1F1E6 + c[0].charCodeAt(0) - 65, 0x1F1E6 + c[1].charCodeAt(0) - 65);
}

export function getCountryByDial(dial: string): CountryEntry | undefined {
  return ALL_COUNTRIES.find((c) => c.dial === dial);
}
