import React from 'react';
import Link from 'next/link';
import {
  FiFileText, FiUserCheck, FiUsers, FiSlash, FiDatabase, FiMapPin, FiCpu,
  FiLink2, FiAlertTriangle, FiXOctagon, FiShield, FiClipboard,
} from 'react-icons/fi';
import { LegalDocument, type LegalSection } from '@/components/ui/legal/legal-document';

function Card({ children }: { children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-5">
      {children}
    </div>
  );
}

const sections: LegalSection[] = [
  {
    id: 'acceptance',
    index: '01',
    icon: <FiFileText />,
    title: 'Acceptance of these terms',
    children: (
      <p>By creating an account, joining an organization, or otherwise using MyndDesk, you agree to these Terms of Use and to our <Link href="/privacy">Privacy Policy</Link>. If you’re accepting on behalf of an organization, you’re confirming you have the authority to bind that organization.</p>
    ),
  },
  {
    id: 'beta',
    index: '02',
    icon: <FiAlertTriangle />,
    title: 'Private beta',
    children: (
      <Card>
        <p className="text-xs text-amber-400/90 font-bold uppercase tracking-widest mb-3">Please read before relying on this product</p>
        <ul className="space-y-2 text-zinc-400 text-sm list-disc pl-5">
          <li>Features may change, move, or be removed as we iterate.</li>
          <li>Pip AI is generated by a cloud model and can be wrong — verify anything important before acting on it.</li>
          <li>Data sync is encrypted but provided as-is during the beta period.</li>
          <li>We work hard on reliability but can’t guarantee zero downtime yet.</li>
        </ul>
      </Card>
    ),
  },
  {
    id: 'eligibility',
    index: '03',
    icon: <FiUserCheck />,
    title: 'Eligibility',
    children: (
      <p>You must be at least 18 years old and legally able to enter into a binding agreement to use MyndDesk. You also confirm you’re not subject to sanctions or on a prohibited-parties list under applicable trade law.</p>
    ),
  },
  {
    id: 'accounts',
    index: '04',
    icon: <FiUsers />,
    title: 'Accounts, organizations & roles',
    children: (
      <>
        <p>MyndDesk is organized around <strong>organizations</strong> — a tenant boundary for your team’s data. You can belong to more than one organization, and each has its own membership and role.</p>
        <p>Every organization member holds a role — <strong>Owner, Admin, Manager, Member,</strong> or <strong>Guest</strong> — which determines what they can see and change, as described fully in our Privacy Policy. Organization owners and admins are responsible for who they invite and what role they grant.</p>
        <p>You’re responsible for keeping your login credentials confidential and for all activity under your account. Tell us immediately if you suspect unauthorized access.</p>
      </>
    ),
  },
  {
    id: 'acceptable-use',
    index: '05',
    icon: <FiSlash />,
    title: 'Acceptable use',
    children: (
      <>
        <p>You may use MyndDesk for your own or your organization’s legitimate business operations. You agree not to:</p>
        <ul className="space-y-2 list-disc pl-5">
          <li>Reverse-engineer, decompile, or attempt to extract the platform’s source code.</li>
          <li>Use bots, scrapers, or automated scripts to interact with the platform outside of normal use.</li>
          <li>Attempt to overload, disrupt, or gain unauthorized access to any part of the platform or another organization’s data.</li>
          <li>Upload content that’s unlawful, infringing, or that you don’t have the right to share.</li>
        </ul>
      </>
    ),
  },
  {
    id: 'your-content',
    index: '06',
    icon: <FiDatabase />,
    title: 'Your content',
    children: (
      <p>You keep ownership of everything you create in MyndDesk — tasks, notes, projects, client records, and files. You’re responsible for its accuracy and for having the right to store it. Within your organization, visibility follows the role rules described in our <Link href="/privacy">Privacy Policy</Link>: an Owner or Admin can see and manage records other members created, exactly as intended for a shared workspace.</p>
    ),
  },
  {
    id: 'location',
    index: '07',
    icon: <FiMapPin />,
    title: 'Attendance & location features',
    children: (
      <p>Attendance is opt-in per organization. If your admin enables it and you grant your browser’s location permission, MyndDesk reads your device’s location to support clock-in/out and presence tracking as described in our Privacy Policy. You can withdraw permission at any time through your browser or device settings; doing so simply disables the automatic parts of the feature.</p>
    ),
  },
  {
    id: 'ai-assistant',
    index: '08',
    icon: <FiCpu />,
    title: 'Pip AI',
    children: (
      <>
        <p>Pip AI is an assistant built on a third-party cloud model. You retain rights to the prompts and data you provide it, and you’re granted full rights to use its output, subject to these terms and applicable law.</p>
        <p>Don’t use Pip AI to generate content that’s unlawful, infringing, or harmful. Because responses are AI-generated, treat them as a starting point — not a substitute for your own judgment, especially for anything with legal, financial, or safety consequences.</p>
      </>
    ),
  },
  {
    id: 'webhooks',
    index: '09',
    icon: <FiLink2 />,
    title: 'Webhooks & integrations',
    children: (
      <p>Organization owners and admins may configure outbound webhooks that forward certain event data (such as attendance events) to a URL of their choosing. Whoever configures a webhook is responsible for the destination and for how that third party handles the data it receives — MyndDesk’s responsibility ends at delivery.</p>
    ),
  },
  {
    id: 'fees',
    index: '10',
    icon: <FiFileText />,
    title: 'Fees',
    children: (
      <p>MyndDesk is currently offered free of charge during the private beta. If we introduce paid plans, pricing and payment terms will be presented to you clearly before anything is charged, and continued use after that point is subject to those terms.</p>
    ),
  },
  {
    id: 'termination',
    index: '11',
    icon: <FiXOctagon />,
    title: 'Suspension & termination',
    children: (
      <p>You can stop using MyndDesk and delete your account at any time. We may suspend or terminate access that violates these terms, poses a security risk, or is required by law, and will make reasonable efforts to notify the account or organization owner first except where that isn’t appropriate (e.g. active abuse).</p>
    ),
  },
  {
    id: 'liability',
    index: '12',
    icon: <FiShield />,
    title: 'Limitation of liability',
    children: (
      <p>To the maximum extent permitted by law, MyndDesk and its affiliates aren’t liable for indirect, incidental, special, or consequential damages — including lost data, revenue, or business opportunities — arising from your use of the platform. The platform is provided “as is” and “as available” during the beta period.</p>
    ),
  },
  {
    id: 'indemnity',
    index: '13',
    icon: <FiClipboard />,
    title: 'Indemnification',
    children: (
      <p>You agree to indemnify and hold MyndDesk harmless from claims, damages, or expenses arising from your use of the platform or a violation of these terms.</p>
    ),
  },
  {
    id: 'governing-law',
    index: '14',
    icon: <FiFileText />,
    title: 'Governing law & changes',
    children: (
      <>
        <p>These terms are governed by the laws applicable in MyndDesk’s place of operation, without regard to conflict-of-law principles, and disputes are resolved through good-faith negotiation in the first instance.</p>
        <p>We may update these terms as the product evolves. We’ll update the “Last updated” date below and, for material changes, let you know in the app before they take effect.</p>
      </>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalDocument
      eyebrow="Terms of Use"
      title={<>Terms of<br />Use</>}
      subtitle="The agreement between you and MyndDesk for using the platform — your organization, your data, and what we each commit to."
      lastUpdated="July 31, 2026"
      meta={['Version 2.0', 'Private beta']}
      highlight={{
        icon: <FiFileText />,
        title: 'The short version',
        body: "Use MyndDesk the way it’s meant to be used, keep your account secure, and remember it’s still in private beta — features move fast and Pip AI’s answers should be checked, not blindly trusted.",
      }}
      sections={sections}
      closing={{
        title: 'Questions about these terms?',
        body: "We’re happy to walk through anything here — reach out and we’ll get back to you.",
        email: 'legal@agbedus.com',
      }}
      siblingHref="/privacy"
      siblingLabel="Privacy Policy"
    />
  );
}
