'use client';

import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { motion } from 'framer-motion';
import { FiArrowLeft, FiAlertCircle, FiShield, FiFileText, FiTarget, FiActivity, FiLock, FiCpu, FiExternalLink, FiDatabase } from 'react-icons/fi';

export default function TermsPage() {
    const fadeIn = {
        initial: { opacity: 0, y: 20 },
        animate: { opacity: 1, y: 0 },
        transition: { duration: 0.6 }
    };

    return (
        <div className="min-h-screen bg-zinc-950 text-zinc-300 font-inter selection:bg-indigo-500/30 selection:text-white noise">
            {/* Top Navigation */}
            <nav className="fixed top-0 w-full z-50 bg-zinc-950/80 backdrop-blur-md border-b border-white/5">
                <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
                    <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
                        <Image src="/logo.svg" alt="MD Logo" width={32} height={32} />
                        <span className="text-xl font-bold tracking-tight text-white">MD<span className="text-emerald-500">Dash</span></span>
                    </Link>
                    <Link 
                        href="/" 
                        className="flex items-center gap-2 text-sm font-medium text-zinc-400 hover:text-white transition-colors"
                    >
                        <FiArrowLeft /> Back to Mission
                    </Link>
                </div>
            </nav>

            <main className="pt-40 pb-24 px-6">
                <div className="max-w-5xl mx-auto space-y-20">
                    {/* Header Section */}
                    <motion.div {...fadeIn} className="space-y-8 border-b border-white/5 pb-16">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-[10px] font-bold uppercase tracking-widest">
                            Operational Governance Directive
                        </div>
                        <h1 className="text-5xl md:text-7xl font-bold tracking-tight text-white leading-[1.1]">Terms of Use <br /> & Service</h1>
                        <p className="text-zinc-500 text-xl max-w-2xl">MD-Dash is an AI-powered productivity platform. Your use of this system is governed by the following terms.</p>
                        <div className="flex items-center gap-6 pt-4 text-xs font-bold uppercase tracking-widest text-zinc-600">
                            <span>Revision: 07.06.2026</span>
                            <span>Version: 1.2.0-Beta</span>
                        </div>
                    </motion.div>

                    {/* Operational Risk Disclosure */}
                    <motion.div 
                        {...fadeIn} 
                        transition={{ delay: 0.1 }}
                        className="p-10 rounded-[3rem] bg-amber-500/5 border border-amber-500/20 space-y-6"
                    >
                        <div className="flex items-center gap-3 text-amber-400 font-bold uppercase tracking-widest text-xs">
                            <FiAlertCircle className="animate-pulse" /> Private Beta Notice
                        </div>
                        <p className="text-zinc-300 leading-relaxed">
                            MD-Dash is currently in private beta. By using the platform, you acknowledge and accept that:
                        </p>
                        <ul className="grid grid-cols-1 md:grid-cols-2 gap-4 list-none pl-0">
                            {[
                                "Features may change or be removed as we iterate.",
                                "AI responses are generated by cloud models and may contain errors.",
                                "Data sync is encrypted but provided as-is during beta.",
                                "We prioritize data integrity but cannot guarantee zero downtime."
                            ].map((note, i) => (
                                <li key={i} className="flex gap-2 text-[10px] font-bold uppercase tracking-widest text-amber-500/70">
                                    <span className="text-amber-500 shrink-0">·</span> {note}
                                </li>
                            ))}
                        </ul>
                    </motion.div>

                    {/* Policy Content */}
                    <div className="space-y-24">
                        {/* Section 1 */}
                        <motion.section {...fadeIn} className="space-y-8">
                            <div className="flex items-start gap-6">
                                <span className="text-4xl font-black text-white/10 shrink-0">01</span>
                                <div className="space-y-4">
                                    <h2 className="text-3xl font-bold text-white">Operational Eligibility</h2>
                                    <p className="text-zinc-400 leading-relaxed">To access the MD-Dash Intelligence System, you must meet the following mandatory requirements:</p>
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
                                        <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 space-y-3">
                                            <h4 className="font-bold text-white uppercase text-xs tracking-widest">Age & Capacity</h4>
                                            <p className="text-xs text-zinc-500">You must be at least 18 years of age and possess the legal capacity to enter into binding operational agreements.</p>
                                        </div>
                                        <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 space-y-3">
                                            <h4 className="font-bold text-white uppercase text-xs tracking-widest">Sanctions Compliance</h4>
                                            <p className="text-xs text-zinc-500">You represent that you are not on any prohibited parties list or under international trade sanctions.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </motion.section>

                        {/* Section 2 */}
                        <motion.section {...fadeIn} className="space-y-8">
                            <div className="flex items-start gap-6">
                                <span className="text-4xl font-black text-white/10 shrink-0">02</span>
                                <div className="space-y-4">
                                    <h2 className="text-3xl font-bold text-white">License to Use</h2>
                                    <p className="text-zinc-400 leading-relaxed">MD-Dash grants you a limited, non-exclusive, non-transferable license to access and use the platform for your personal or business operations.</p>
                                    <div className="p-6 rounded-2xl bg-indigo-500/5 border border-indigo-500/10">
                                         <h4 className="text-xs font-bold uppercase tracking-widest text-indigo-400 mb-4 flex items-center gap-2">
                                            <FiShield /> Restricted Activities
                                         </h4>
                                         <ul className="space-y-3 text-xs text-zinc-500 list-disc pl-5">
                                            <li>Reverse-engineering, decompiling, or attempting to extract the source code of the platform.</li>
                                            <li>Using automated scripts or bots to interact with the platform beyond normal usage patterns.</li>
                                            <li>Attempting to overload, crash, or disrupt the platform infrastructure.</li>
                                            <li>Unauthorized scraping or crawling of the platform.</li>
                                         </ul>
                                    </div>
                                </div>
                            </div>
                        </motion.section>

                        {/* Section 3 */}
                        <motion.section {...fadeIn} className="space-y-8">
                            <div className="flex items-start gap-6">
                                <span className="text-4xl font-black text-white/10 shrink-0">03</span>
                                <div className="space-y-4">
                                    <h2 className="text-3xl font-bold text-white">Your Responsibility</h2>
                                    <p className="text-zinc-400 leading-relaxed">You are responsible for maintaining the security of your account and the data you store on the platform.</p>
                                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                                        <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 space-y-3">
                                            <FiLock className="text-indigo-400 text-xl" />
                                            <h4 className="font-bold text-white text-sm">Account Security</h4>
                                            <p className="text-[10px] text-zinc-500 leading-relaxed">You are responsible for safeguarding your password and authentication credentials. We cannot recover lost or stolen access keys.</p>
                                        </div>
                                        <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 space-y-3">
                                            <FiDatabase className="text-emerald-400 text-xl" />
                                            <h4 className="font-bold text-white text-sm">Data Backup</h4>
                                            <p className="text-[10px] text-zinc-500 leading-relaxed">Your data is yours. We recommend maintaining regular backups of important information stored on the platform.</p>
                                        </div>
                                        <div className="p-6 rounded-2xl bg-white/[0.02] border border-white/5 space-y-3">
                                            <FiActivity className="text-zinc-400 text-xl" />
                                            <h4 className="font-bold text-white text-sm">Compliance</h4>
                                            <p className="text-[10px] text-zinc-500 leading-relaxed">You are responsible for ensuring your use of MD-Dash complies with all applicable laws and regulations in your jurisdiction.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </motion.section>

                        {/* Section 4 */}
                        <motion.section {...fadeIn} className="space-y-8">
                            <div className="flex items-start gap-6">
                                <span className="text-4xl font-black text-white/10 shrink-0">04</span>
                                <div className="space-y-4">
                                    <h2 className="text-3xl font-bold text-white">AI Assistant & Output Rights</h2>
                                    <p className="text-zinc-400 leading-relaxed">Interactions with Pip AI, the MD-Dash AI assistant, are subject to the following terms.</p>
                                    <div className="space-y-6">
                                        <div className="prose prose-invert prose-sm max-w-none text-zinc-500">
                                            <p><strong>Your Input:</strong> You retain all intellectual property rights to the data and prompts you provide to Pip AI.</p>
                                            <p><strong>AI Output:</strong> MD-Dash grants you full rights to the content generated by Pip AI in response to your prompts, subject to your compliance with these terms.</p>
                                            <p><strong>Acceptable Use:</strong> You may not use Pip AI to generate content that violates applicable law, infringes on third-party rights, or promotes harmful or illegal activities.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </motion.section>

                        {/* Section 5 */}
                        <motion.section {...fadeIn} className="space-y-8">
                            <div className="flex items-start gap-6">
                                <span className="text-4xl font-black text-white/10 shrink-0">05</span>
                                <div className="space-y-4">
                                    <h2 className="text-3xl font-bold text-white">Limitation of Liability</h2>
                                    <div className="p-8 rounded-[2rem] bg-zinc-900 border border-white/10 text-sm leading-relaxed text-zinc-400">
                                        To the maximum extent permitted by law, MD-Dash and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of data, revenue, or business opportunities, arising from your use of the platform. MD-Dash provides the platform on an "as is" and "as available" basis during the private beta phase.
                                    </div>
                                </div>
                            </div>
                        </motion.section>

                        {/* Section 6 */}
                        <motion.section {...fadeIn} className="space-y-8">
                            <div className="flex items-start gap-6">
                                <span className="text-4xl font-black text-white/10 shrink-0">06</span>
                                <div className="space-y-4">
                                    <h2 className="text-3xl font-bold text-white">Indemnification</h2>
                                    <p className="text-zinc-400 leading-relaxed text-sm">You agree to indemnify and hold harmless MD-Dash from any claims, damages, or expenses arising from your use of the platform or violation of these terms.</p>
                                </div>
                            </div>
                        </motion.section>

                        {/* Section 7 */}
                        <motion.section {...fadeIn} className="space-y-8">
                            <div className="flex items-start gap-6">
                                <span className="text-4xl font-black text-white/10 shrink-0">07</span>
                                <div className="space-y-4">
                                    <h2 className="text-3xl font-bold text-white">Governing Law</h2>
                                    <p className="text-zinc-400 leading-relaxed text-sm">These terms are governed by the laws of Delaware, United States. Any disputes shall be resolved through binding individual arbitration.</p>
                                </div>
                            </div>
                        </motion.section>
                    </div>

                    {/* Final Banner */}
                    <motion.div 
                        {...fadeIn}
                        className="p-12 rounded-[3.5rem] bg-white/[0.02] border border-white/5 space-y-8 relative overflow-hidden"
                    >
                        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/5 blur-[100px] -z-10" />
                        <div className="max-w-3xl mx-auto space-y-6 text-center">
                            <h2 className="text-3xl font-bold text-white">Questions?</h2>
                            <p className="text-zinc-500 leading-relaxed">If you have any questions about these terms, please reach out to our team.</p>
                            <div className="flex flex-col md:flex-row items-center justify-center gap-6 pt-4">
                                <Link href="mailto:legal@md-dash.com" className="flex items-center gap-2 text-indigo-400 font-bold hover:text-indigo-300 transition-colors">
                                    legal@md-dash.com <FiExternalLink />
                                </Link>
                                <span className="w-1 h-1 rounded-full bg-zinc-700 hidden md:block" />
                                <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-zinc-600">Private Beta v1.2</span>
                            </div>
                        </div>
                    </motion.div>
                </div>
            </main>

            <footer className="py-20 border-t border-white/5">
                <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-8 text-[10px] font-bold uppercase tracking-widest text-zinc-600">
                    <div className="flex items-center gap-6">
                        <FiCpu className="text-lg text-indigo-500/50" />
                        <span>MD-Dash Intelligence Platform</span>
                    </div>
                    <div className="flex items-center gap-8">
                        <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
                        <span>Beta v1.2</span>
                    </div>
                </div>
            </footer>
        </div>
    );
}
